### ISSUE TITLE
: Is bool KinodynamicSearch::entanglesWithStaticObs(KNodePtr current) method implemented?

### ISSUE THREAD

**Issue by abdelhakim96** [caomuqing/neptune#2]
Hello,

I noticed that the method bool KinodynamicSearch::entanglesWithStaticObs(KNodePtr current) in the KinodynamicSearch class appears to be commented out. Could you confirm if this method has been implemented, or is it intended to be completed in the future?

Thank you for your help!

**Comment by caomuqing** [comment]
Hi Hakim,

Thanks for your interest. The obstacles are handled in the function KinodynamicSearch::entanglesWithOtherAgents. If you look into the function, there is another call for the function eu::entangleHSigToAddStatic, that's where the static obstacles are considered. KinodynamicSearch::entanglesWithStaticObs was an old way of doing this but I decided to put them together because entanglement of obstacles and other agents cannot be uncoupled.

Hope that helps.

**Comment by abdelhakim96** [comment]
Thanks, Muqing, for the clarification! I appreciate your help!
